### ISSUE TITLE
[Bug]: Panic when deleting disk after new one is created

### ISSUE THREAD

**Issue by yzguy** [linode/terraform-provider-linode#1212]
### Terraform Version

Terraform v1.6.4 on linux amd64

### Linode Provider Version

version = "2.11.0"

### Effected Terraform Resources

linode_instance_disk

### Terraform Config Files

```
resource "linode_instance_disk" "boot" {
  label     = "Boot"
  linode_id = linode_instance.instance.id
  size      = (linode_instance.instance.specs.0.disk / 2) - 512
  image     = data.linode_images.image.images.0.id

  lifecycle {
    create_before_destroy = true
  }
}

resource "linode_instance_disk" "swap" {
  label      = "Swap"
  linode_id  = linode_instance.router.id
  size       = 512
  filesystem = "swap"
}

resource "linode_instance_config" "instance_config" {
  label     = local.hostname
  linode_id = linode_instance.instance.id

  device {
    device_name = "sda"
    disk_id     = linode_instance_disk.boot.id
  }

  device {
    device_name = "sdb"
    disk_id     = linode_instance_disk.swap.id
  }

  kernel = "linode/grub2"

  booted = true

  helpers {
    network = false
  }
}

resource "linode_instance" "instance" {
  label  = local.hostname
  region = module.region.id
  type   = var.size

  watchdog_enabled = true

  tags = distinct(concat(local.tags, var.tags))
}
```

### Panic Output

```
Stack trace from the terraform-provider-linode_v2.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb44ae0]

goroutine 373 [running]:
github.com/linode/linodego.eventMatchesSecondary(...)
github.com/linode/linodego@v1.26.0/waitfor.go:790
github.com/linode/linodego.(*EventPoller).WaitForLatestUnknownEvent(0xc00070cc00, {0x26f5768, 0xc0009e41b0})
github.com/linode/linodego@v1.26.0/waitfor.go:672 +0x820
github.com/linode/linodego.(*EventPoller).WaitForFinished(0xc00070cc00, {0x26f57a0?, 0xc000992d80?}, 0x2354bc5?)
github.com/linode/linodego@v1.26.0/waitfor.go:700 +0xec
github.com/linode/terraform-provider-linode/v2/linode/instancedisk.deleteResource({0x26f5768?, 0xc000992b40?}, 0xc000977300, {0x1ec9000?, 0xc000238600})
github.com/linode/terraform-provider-linode/v2/linode/instancedisk/resource.go:296 +0x73a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000405b20, {0x26f57a0, 0xc0008a9ec0}, 0xd?, {0x1ec9000, 0xc000238600})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:829 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000405b20, {0x26f57a0, 0xc0008a9ec0}, 0xc00094e410, 0xc000977280, {0x1ec9000, 0xc000238600})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:878 +0x60a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00059cd08, {0x26f57a0?, 0xc0008a9da0?}, 0xc0005b4c30)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x26f56f8?, {0x26f57a0?, 0xc0008a9a70?}, 0xc0005b4c30)
github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00035e3c0, {0x26f57a0?, 0xc0008a9260?}, 0xc00035c150)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x22b72c0?, 0xc00035e3c0}, {0x26f57a0, 0xc0008a9260}, 0xc000977000, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000240960, {0x26f57a0, 0xc0008a91d0}, {0x26fdf98, 0xc0003fa680}, 0xc00074c6c0, 0xc000664420, 0x372f8b8, 0x0)
google.golang.org/grpc@v1.60.0/server.go:1372 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000240960, {0x26fdf98, 0xc0003fa680}, 0xc00074c6c0)
google.golang.org/grpc@v1.60.0/server.go:1783 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.60.0/server.go:1016 +0x68
created by google.golang.org/grpc.(*Server).serveStreams.func2
google.golang.org/grpc@v1.60.0/server.go:1027 +0x12e

Error: The terraform-provider-linode_v2.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

### Expected Behavior

New disk is created, old disk is deleted

### Actual Behavior

New disk is created,nd then old disk is "deleting" but hits a panic

### Steps to Reproduce

Instance with disk/config is running, swap out the image the boot disk starts from, apply changes (error happens)

Just for another data point I went back to v2.10.1 and it works fine so it's definitely [this commit](https://github.com/linode/terraform-provider-linode/commit/ecb7255cdf0857893fa60e86f11a35d92828f59a)

**Comment by zliang-akamai** [comment]
Thank you so much for the bug report! This issue has been fixed in [`v2.13.0`](https://github.com/linode/terraform-provider-linode/releases/tag/v2.13.0). You can upgrade your Linode Terraform Provider to test it. Let us know if there is still any issue or question.
