### ISSUE TITLE
[Bug]: error in `instanceconfig.expandDevicesBlock()`

### ISSUE THREAD

**Issue by ngfeldman** [linode/terraform-provider-linode#1536]
### Terraform Version

OpenTofu v1.8.0 on linux_amd64

### Linode Provider Version

2.25.0

### Effected Terraform Resources

linode_instance_config

### Terraform Config Files

```terraform
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 2.25"
    }
  }
}

variable "linode_api_token" {
  type      = string
  sensitive = true
}

variable "linode_volume_id" {
  type = string
}

provider "linode" {
  token = var.linode_api_token
}

data "linode_user" "me" {
  username = "nfeldman"
}

data "linode_sshkeys" "ssh_keys" {
  filter {
    name   = "label"
    values = data.linode_user.me.ssh_keys
  }
}

locals {
  user_data = templatefile(
    "${path.module}/user-data.yaml.tftpl",
    { sshkeys = data.linode_sshkeys.ssh_keys.sshkeys },
  )
}

resource "linode_instance" "instance" {
  label            = "production-docker-host"
  image            = "linode/ubuntu24.04"
  region           = "us-west"
  type             = "g6-nanode-1"
  authorized_users = [data.linode_user.me.username]
  metadata {
    user_data = base64encode(local.user_data)
  }
}

resource "linode_instance_config" "instance_config" {
  linode_id = linode_instance.instance.id
  label     = "my-config"
  device {
    device_name = "linode-volume"
    volume_id   = var.linode_volume_id
  }
}

output "instance_ip_address" {
  value = linode_instance.instance.ip_address
}

output "user_data" {
  value = local.user_data
}
```

### Debug Output

```
Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

linode_instance.instance: Creating...
linode_instance.instance: Still creating... [10s elapsed]
linode_instance.instance: Still creating... [20s elapsed]
linode_instance.instance: Still creating... [30s elapsed]
linode_instance.instance: Still creating... [40s elapsed]
linode_instance.instance: Creation complete after 50s [id=62258928]
linode_instance_config.instance_config: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with linode_instance_config.instance_config,
│   on main.tf line 52, in resource "linode_instance_config" "instance_config":
│   52: resource "linode_instance_config" "instance_config" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-linode_v2.25.0 plugin:

panic: reflect: call of reflect.Value.Set on zero Value

goroutine 157 [running]:
reflect.flag.mustBeAssignableSlow(0x0?)
	reflect/value.go:265 +0x105
reflect.flag.mustBeAssignable(...)
	reflect/value.go:259
reflect.Value.Set({0x0?, 0x0?, 0xc00013ced0?}, {0x1e7a320?, 0xc000b10010?, 0xa79280?})
	reflect/value.go:2254 +0x65
github.com/linode/terraform-provider-linode/v2/linode/instanceconfig.expandDevicesBlock({0x2245440?, 0xc0000a75a0})
	github.com/linode/terraform-provider-linode/v2/linode/instanceconfig/helper.go:127 +0x46e
github.com/linode/terraform-provider-linode/v2/linode/instanceconfig.createResource({0x270c1d0?, 0xc0002c51f0?}, 0x0?, {0x1e77aa0?, 0xc00085e000?})
	github.com/linode/terraform-provider-linode/v2/linode/instanceconfig/resource.go:158 +0x67a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000019ce0, {0x270c128, 0xc0007d8900}, 0xd?, {0x1e77aa0, 0xc00085e000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:806 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000019ce0, {0x270c128, 0xc0007d8900}, 0xc0001f4340, 0xc000720a00, {0x1e77aa0, 0xc00085e000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000139bd8, {0x270c128?, 0xc0007d8810?}, 0xc00083ec30)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x270c160?, {0x270c128?, 0xc0007d8510?}, 0xc00083ec30)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000c88c0, {0x270c128?, 0xc0005bbce0?}, 0xc0002c4af0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x22a4b80?, 0xc0000c88c0}, {0x270c128, 0xc0005bbce0}, 0xc000720600, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001dee00, {0x270c128, 0xc0005bbc50}, {0x27186d8, 0xc0002d6a80}, 0xc0007d4b40, 0xc000788450, 0x37f64f8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001dee00, {0x27186d8, 0xc0002d6a80}, 0xc0007d4b40)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 42
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-linode_v2.25.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Panic Output

N/A

### Expected Behavior

The provider should have created the `linode_instance_config` resource and attached my volume to the instance at /dev/linode-volume

### Actual Behavior

The instance is created, user data is run, and I can SSH into it, but my volume remains unattached and I do not see /dev/linode-volume inside the instance.

### Steps to Reproduce

environment variables:

- `TF_VAR_linode_api_token` set to my personal API token
- `TF_VAR_linode_volume_id` set to `202894`

The volume is managed outside of OpenTofu/Terraform. I found the integer ID by running a `curl` command against https://api.linode.com/v4/volumes

**Comment by ngfeldman** [comment]
I'm guessing that the provider is trying to make this request behind the scenes:

```sh
curl --request POST \
    --url https://api.linode.com/v4/linode/instances/${instance_id}/configs \
    --header "authorization: Bearer ${TF_VAR_linode_api_token}" \
    --header 'accept: application/json'  \
    --header 'content-type: application/json' \
    --data '{"label": "my-config", "devices": {"linode-volume": "${TF_VAR_linode_volume_id}"}}'
```

Looking at the [API documentation](https://techdocs.akamai.com/linode-api/reference/post-add-linode-config), it seems like the device name has to be one of `sda`, `sdb`, ... `sdh`, and I was under a misconception that Linux would allow the user to create devices with arbitrary names. This command gives me this error response:

```
{"errors": [{"reason": "Device linode-volume is not valid for assignment"}, {"reason": "Invalid mapping for linode-volume, should be an Object containing 'disk_id' or 'volume_id'"}]}
```

Replacing `linode-volume` with `sdb` in my code gets me past this particular error (though I'm still having problems getting cloud-init to mount the device successfully).

I still think it's a bug with the linode terraform provider that it accepts arbitrary device names even though the underlying device does not. The [provider documentation](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_config) should also be updated to reflect this.

**Comment by zliang-akamai** [comment]
@ngfeldman Thanks for the information! You are correct. I will be working adding validation logic to the `device_name` attribute.
