### ISSUE TITLE
[Bug]: linode_instance creation crashes on empty authorized_keys

### ISSUE THREAD

**Issue by tomasbedrich** [linode/terraform-provider-linode#714]
### Terraform Version

Terraform v1.1.7

### Linode Provider Version

v1.29.4

### Terraform Config Files

```
resource "tls_private_key" "website" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P224"  # because of this, public_key_openssh attribute is not populated => empty
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.website.private_key_pem
  filename        = "xxx-website-root.pem"
  file_permission = "0600"
}

data "linode_profile" "me" {}

resource "linode_instance" "website" {
  label            = "xxx-website"
  region           = "eu-central"
  type             = "g6-standard-1"
  image            = "linode/ubuntu22.04"
  authorized_keys  = [chomp(tls_private_key.website.public_key_openssh)]
  authorized_users = [data.linode_profile.me.username]
  backups_enabled  = true
  watchdog_enabled = true
}
```

### Debug Output

```
$ TF_LINODE=DEBUG LINODE_DEBUG=1 tf apply

...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # linode_instance.website will be created
  + resource "linode_instance" "website" {
      + authorized_keys    = [
          + "",  # <<<<<<<<<<<<<<<<<<<<<<<
        ]
      + authorized_users   = [
          + "xxx",
        ]
      + backups            = (known after apply)
      + backups_enabled    = true
      + boot_config_label  = (known after apply)
      + booted             = (known after apply)
      + id                 = (known after apply)
      + image              = "linode/ubuntu22.04"
      + ip_address         = (known after apply)
      + ipv4               = (known after apply)
      + ipv6               = (known after apply)
      + label              = "xxx-website"
      + private_ip_address = (known after apply)
      + region             = "eu-central"
      + resize_disk        = false
      + shared_ipv4        = (known after apply)
      + specs              = (known after apply)
      + status             = (known after apply)
      + swap_size          = (known after apply)
      + type               = "g6-standard-1"
      + watchdog_enabled   = true

      + alerts {
          + cpu            = (known after apply)
          + io             = (known after apply)
          + network_in     = (known after apply)
          + network_out    = (known after apply)
          + transfer_quota = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + website_ip = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

linode_instance.website: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with linode_instance.website,
│   on dev-machine.tf line 132, in resource "linode_instance" "website":
│  132: resource "linode_instance" "website" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-linode_v1.29.4 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 25 [running]:
github.com/linode/terraform-provider-linode/linode/instance.createResource({0x2c32b88, 0xc000ba0960}, 0x0?, {0x24ab220?, 0xc00019a2c0})
        github.com/linode/terraform-provider-linode/linode/instance/resource.go:190 +0x259d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000371420, {0x2c32bc0, 0xc000975230}, 0xd?, {0x24ab220, 0xc00019a2c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000371420, {0x2c32bc0, 0xc000975230}, 0xc000cb0c30, 0xc000d03080, {0x24ab220, 0xc00019a2c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000df80, {0x2c32bc0?, 0xc000975110?}, 0xc000972500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00056e820, {0x2c32bc0?, 0xc000974900?}, 0xc000c98150)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x276ad80?, 0xc00056e820}, {0x2c32bc0, 0xc000974900}, 0xc000c980e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x2c36940, 0xc000602d00}, 0xc000576120, 0xc0005af7a0, 0x3959fc0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x2c36940, 0xc000602d00}, 0xc000576120, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-linode_v1.29.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

The provider should crash gracefully saying something along the lines: "authorized_keys cannot be empty string ..."

### Actual Behavior

The provider crashes with stacktrace.

### Steps to Reproduce

Try to create linode_instance with a single authorized_key, which is empty string. (See the abovementioned TF snippet)

**Comment by LBGarber** [comment]
Thanks for the report!

I've put up PR #715 to add graceful error handling for unexpected `authorized_keys` and `authorized_users` values.

Let me know if you run into any other issues :slightly_smiling_face:
