### ISSUE TITLE
[Bug]: Crash after 2.7.0 update

### ISSUE THREAD

**Issue by codedumper** [linode/terraform-provider-linode#992]
### Terraform Version

Terraform v1.5.6 on darwin_arm64

### Linode Provider Version

version = "2.7.0"

### Effected Terraform Resources

linode_instance_config

### Terraform Config Files

variable "zabbix" {
  type = object({
    label         = optional(string, "test")
    image         = string
    instance_type = string
    interface = object({
      purpose = string
      label   = optional(string, null)
      network = optional(string, null)
      host    = optional(number, null)
    })

    storage = map(
      object({
        type       = optional(string, "disk") # Could be disk or volume
        size       = string                   # Sise in Mb
        filesystem = optional(string)         # Required for disk only
      })
    )
    zabbix_db_name     = optional(string, "zabbix")
    zabbix_db_username = optional(string, "zabbix")
    zabbix_db_password = string

  })
}

# Architecture Level
module "zabbix" {
  source = "../../modules/linode-instance"
  label  = var.zabbix.label

  governance    = var.governance
  ssh_keys      = var.ssh_keys
  root_password = var.root_password

  image          = var.zabbix.image
  instance_type  = var.zabbix.instance_type
  interfaces     = [var.zabbix.interface]
  network_helper = true

  stackscript_id = module.zabbix_stackscript.id
  stackscript_data = {
    "hostname"           = var.zabbix.label
    "gateway"            = cidrhost(var.zabbix.interface.network, 1)
    "data_volume"        = "sdc"
    "zabbix_db_name"     = var.zabbix.zabbix_db_name
    "zabbix_db_username" = var.zabbix.zabbix_db_username
    "zabbix_db_password" = var.zabbix.zabbix_db_password
  }
  storage = var.zabbix.storage

  tags = local.tags

  depends_on = [
    module.zabbix_stackscript
  ]
}

# Infrastructure Level

resource "linode_instance_config" "config" {
  label       = module.config_naming.name
  booted      = var.booted
  kernel      = "linode/latest-64bit"
  linode_id   = linode_instance.instance.id
  root_device = "/dev/${var.root_device}"

  # device = { for device, value in var.storage : device => value }

  dynamic "device" {
    for_each = var.storage
    content {
      device_name = device.key
      disk_id     = device.value.type == "disk" ? linode_instance_disk.disks[device.key].id : null
      volume_id   = device.value.type == "volume" ? linode_volume.volumes[device.key].id : null
    }
  }

  dynamic "interface" {
    for_each = var.interfaces
    content {
      purpose      = interface.value.purpose
      label        = interface.value.purpose == "public" ? null : module.vlan_naming[interface.value.label].name
      ipam_address = interface.value.purpose == "public" ? null : "${cidrhost(interface.value.network, interface.value.host)}/${split("/", interface.value.network)[1]}"
    }
  }

  helpers {
    network = var.network_helper
  }
}

### Panic Output

module.zabbix.linode_instance_config.config: Modifying... [id=50761086]
╷
│ Error: Plugin did not respond
│ 
│   with module.zabbix.linode_instance_config.config,
│   on ../../modules/linode-instance/instance_config.tf line 16, in resource "linode_instance_config" "config":
│   16: resource "linode_instance_config" "config" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-linode_v2.7.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 156 [running]:
github.com/linode/terraform-provider-linode/linode/instanceconfig.expandDevicesBlock({0x103fd30c0?, 0x1400094aec0})
        github.com/linode/terraform-provider-linode/linode/instanceconfig/helper.go:121 +0x4b4
github.com/linode/terraform-provider-linode/linode/instanceconfig.updateResource({0x1040c2568, 0x140000ee8a0}, 0x1400086f780, {0x103ce6aa0?, 0x14000259d40})
        github.com/linode/terraform-provider-linode/linode/instanceconfig/resource.go:199 +0x29c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000767960, {0x1040c25a0, 0x140008a5e00}, 0xd?, {0x103ce6aa0, 0x14000259d40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:812 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000767960, {0x1040c25a0, 0x140008a5e00}, 0x140001909c0, 0x1400086f500, {0x103ce6aa0, 0x14000259d40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:919 +0x6a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000198d80, {0x1040c25a0?, 0x140008a5bf0?}, 0x14000971860)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:1027 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140002083f0, 0x14000954d20, 0x14000208450, 0x140002084e0, {0x140000a2d80, 0x2, 0x2}}, {0x1040c25a0?, 0x140008a5500?}, 0x14000971860)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x100
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000719860, {0x1040c25a0?, 0x140008a4cc0?}, 0x140000e65b0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103fd2f60?, 0x14000719860}, {0x1040c25a0, 0x140008a4cc0}, 0x140000e6540, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400035a000, {0x1040ca060, 0x14000093860}, 0x14000be47e0, 0x14000810de0, 0x104e779e0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x1400035a000, {0x1040ca060, 0x14000093860}, 0x14000be47e0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x16c

Error: The terraform-provider-linode_v2.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

No change in interface since upgrade. 
It looks there is a mapping issue in interface block since 2.7.0.
I am upgrading from 2.5.1.

### Actual Behavior

Plugin crashed.

I will dig into issue, but i opened the issue immediately because it could affect other developers.

### Steps to Reproduce

I just upgraded the plugin.

destroy and apply the current instance.

**Comment by codedumper** [comment]
Digging into issue, it comes from the new device map in linux_instance_config.

The error shows : [github.com/linode/terraform-provider-linode/linode/instanceconfig.expandDevicesBlock](panic: interface conversion: interface {} is *schema.Set, not []interface {})

But the trace shows github.com/linode/terraform-provider-linode/linode/instanceconfig.expandDevicesBlock related to devices.

My guess is a shared method used by interfaces and devices mapping has been affected by the new device mapping change.

**Comment by zliang-akamai** [comment]
Hi @codedumper ,we just published v2.7.1 to fix this issue. Thanks for reporting!

**Comment by codedumper** [comment]
I confirm 2.7.1 release solved the case.
